# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kauth': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcompletion': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kconfigwidgets': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/kdeclarative': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kidletime': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kjobwidgets': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwallet': '@latest'
    'frameworks/kwidgetsaddons': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'frameworks/solid': '@latest'
    'frameworks/syntax-highlighting': '@latest'

- 'on': ['Linux/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kauth': '@latest-kf6'
    'frameworks/kcodecs': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdeclarative': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kidletime': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kjobwidgets': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/solid': '@latest-kf6'
    'frameworks/syntax-highlighting': '@latest-kf6'
